<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="17" total="23" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="tempto-tests" duration-ms="81228" started-at="2015-10-05T17:30:35Z" finished-at="2015-10-05T17:31:56Z">
    <groups>
      <group name="hive_convention">
        <method signature="sample_hive_table.allRows()[pri:0, instance:com.teradata.tempto.sample_hive_table@4602fa2f]" name="allRows" class="com.teradata.tempto.sample_hive_table"/>
      </group> <!-- hive_convention -->
      <group name="psql_convention">
        <method signature="sample_psql_table.allRows()[pri:0, instance:com.teradata.tempto.sample_psql_table@7424a39e]" name="allRows" class="com.teradata.tempto.sample_psql_table"/>
        <method signature="sample_psql_table.allRowsOnPsql2()[pri:0, instance:com.teradata.tempto.sample_psql_table@2526ecb7]" name="allRowsOnPsql2" class="com.teradata.tempto.sample_psql_table"/>
      </group> <!-- psql_convention -->
      <group name="query">
        <method signature="SimpleQueryTest.createAndDropMutableTable()[pri:0, instance:com.teradata.tempto.examples.SimpleQueryTest@786125a6]" name="createAndDropMutableTable" class="com.teradata.tempto.examples.SimpleQueryTest"/>
        <method signature="SimpleQueryTest.selectAllFromMultipleTables()[pri:0, instance:com.teradata.tempto.examples.SimpleQueryTest@786125a6]" name="selectAllFromMultipleTables" class="com.teradata.tempto.examples.SimpleQueryTest"/>
        <method signature="SimpleQueryTest.selectAllFromNation()[pri:0, instance:com.teradata.tempto.examples.SimpleQueryTest@786125a6]" name="selectAllFromNation" class="com.teradata.tempto.examples.SimpleQueryTest"/>
        <method signature="SimpleQueryTest.selectCountFromNation()[pri:0, instance:com.teradata.tempto.examples.SimpleQueryTest@786125a6]" name="selectCountFromNation" class="com.teradata.tempto.examples.SimpleQueryTest"/>
      </group> <!-- query -->
      <group name="smoke">
        <method signature="SimpleQueryTest.selectCountFromNation()[pri:0, instance:com.teradata.tempto.examples.SimpleQueryTest@786125a6]" name="selectCountFromNation" class="com.teradata.tempto.examples.SimpleQueryTest"/>
      </group> <!-- smoke -->
      <group name="example_smoketest">
        <method signature="TpchDataSourceTest.testDataSource()[pri:0, instance:com.teradata.tempto.examples.TpchDataSourceTest@53e6b541]" name="testDataSource" class="com.teradata.tempto.examples.TpchDataSourceTest"/>
        <method signature="allRows.query_1()[pri:0, instance:com.teradata.tempto.allRows@7dd3f20e]" name="query_1" class="com.teradata.tempto.allRows"/>
        <method signature="allRows.query_2()[pri:0, instance:com.teradata.tempto.allRows@1dfadb7]" name="query_2" class="com.teradata.tempto.allRows"/>
      </group> <!-- example_smoketest -->
      <group name="presto_convention">
        <method signature="sample_presto_table.allRows()[pri:0, instance:com.teradata.tempto.sample_presto_table@6a4bd9e4]" name="allRows" class="com.teradata.tempto.sample_presto_table"/>
        <method signature="sample_presto_table.psqlOverPrestoAllRows()[pri:0, instance:com.teradata.tempto.sample_presto_table@8ea1521]" name="psqlOverPrestoAllRows" class="com.teradata.tempto.sample_presto_table"/>
      </group> <!-- presto_convention -->
      <group name="ssh">
        <method signature="ExampleSshClientUsage.dynamicSshClient()[pri:0, instance:com.teradata.tempto.examples.ExampleSshClientUsage@3c32f3d8]" name="dynamicSshClient" class="com.teradata.tempto.examples.ExampleSshClientUsage"/>
        <method signature="ExampleSshClientUsage.longRunningCommandTimeout()[pri:0, instance:com.teradata.tempto.examples.ExampleSshClientUsage@3c32f3d8]" name="longRunningCommandTimeout" class="com.teradata.tempto.examples.ExampleSshClientUsage"/>
        <method signature="ExampleSshClientUsage.sshClientUsage()[pri:0, instance:com.teradata.tempto.examples.ExampleSshClientUsage@3c32f3d8]" name="sshClientUsage" class="com.teradata.tempto.examples.ExampleSshClientUsage"/>
      </group> <!-- ssh -->
      <group name="insert">
        <method signature="sample_table_insert.insert_0()[pri:0, instance:com.teradata.tempto.sample_table_insert@1196950e]" name="insert_0" class="com.teradata.tempto.sample_table_insert"/>
        <method signature="sample_table_insert.insert_1()[pri:0, instance:com.teradata.tempto.sample_table_insert@490dc900]" name="insert_1" class="com.teradata.tempto.sample_table_insert"/>
      </group> <!-- insert -->
      <group name="generated">
        <method signature="nation.generated_nation()[pri:0, instance:com.teradata.tempto.nation@7a90796c]" name="generated_nation" class="com.teradata.tempto.nation"/>
      </group> <!-- generated -->
      <group name="psql_query">
        <method signature="PostgresqlQueryTest.selectFromImmutableTable()[pri:0, instance:com.teradata.tempto.examples.PostgresqlQueryTest@17f4276b]" name="selectFromImmutableTable" class="com.teradata.tempto.examples.PostgresqlQueryTest"/>
        <method signature="PostgresqlQueryTest.selectFromMutableTable()[pri:0, instance:com.teradata.tempto.examples.PostgresqlQueryTest@17f4276b]" name="selectFromMutableTable" class="com.teradata.tempto.examples.PostgresqlQueryTest"/>
      </group> <!-- psql_query -->
      <group name="failing">
        <method signature="SimpleQueryTest.failingTest()[pri:0, instance:com.teradata.tempto.examples.SimpleQueryTest@786125a6]" name="failingTest" class="com.teradata.tempto.examples.SimpleQueryTest"/>
      </group> <!-- failing -->
      <group name="injection">
        <method signature="InjectionTest.testInjection()[pri:0, instance:com.teradata.tempto.examples.InjectionTest@46700301]" name="testInjection" class="com.teradata.tempto.examples.InjectionTest"/>
      </group> <!-- injection -->
      <group name="blah">
        <method signature="allRows.query_1()[pri:0, instance:com.teradata.tempto.allRows@7dd3f20e]" name="query_1" class="com.teradata.tempto.allRows"/>
        <method signature="allRows.query_2()[pri:0, instance:com.teradata.tempto.allRows@1dfadb7]" name="query_2" class="com.teradata.tempto.allRows"/>
      </group> <!-- blah -->
    </groups>
    <test name="all" duration-ms="81228" started-at="2015-10-05T17:30:35Z" finished-at="2015-10-05T17:31:56Z">
      <class name="com.teradata.tempto.examples.InjectionTest">
        <test-method status="PASS" signature="testInjection()[pri:0, instance:com.teradata.tempto.examples.InjectionTest@46700301]" name="testInjection" duration-ms="99" started-at="2015-10-05T13:31:56Z" finished-at="2015-10-05T13:31:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInjection -->
      </class> <!-- com.teradata.tempto.examples.InjectionTest -->
      <class name="com.teradata.tempto.nation">
        <test-method status="FAIL" signature="generated_nation()[pri:0, instance:com.teradata.tempto.nation@7a90796c]" test-instance-name="sql_tests.testcases.generated.nation.generated_nation" name="generated_nation" duration-ms="325" started-at="2015-10-05T13:31:19Z" finished-at="2015-10-05T13:31:20Z">
          <exception class="java.lang.NoClassDefFoundError">
            <message>
              <![CDATA[com/facebook/presto/hive/$internal/com/google/common/primitives/Ints]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NoClassDefFoundError: com/facebook/presto/hive/$internal/com/google/common/primitives/Ints
	at org.apache.hive.service.cli.Column.<init>(Column.java:149)
	at org.apache.hive.service.cli.ColumnBasedSet.<init>(ColumnBasedSet.java:51)
	at org.apache.hive.service.cli.RowSetFactory.create(RowSetFactory.java:37)
	at org.apache.hive.jdbc.HiveQueryResultSet.next(HiveQueryResultSet.java:333)
	at com.teradata.tempto.query.QueryResult$QueryResultBuilder.addRows(QueryResult.java:230)
	at com.teradata.tempto.query.QueryResult.forResultSet(QueryResult.java:178)
	at com.teradata.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:102)
	at com.teradata.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:85)
	at com.teradata.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:62)
	at com.teradata.tempto.internal.convention.sql.SqlQueryConventionBasedTest.runTestQuery(SqlQueryConventionBasedTest.java:116)
	at com.teradata.tempto.internal.convention.sql.SqlQueryConventionBasedTest.test(SqlQueryConventionBasedTest.java:94)
	at com.teradata.tempto.internal.convention.ConventionBasedTestProxyGenerator$ConventionBasedTestProxy.test(ConventionBasedTestProxyGenerator.java:120)
	at com.teradata.tempto.nation.generated_nation(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.teradata.tempto.runner.TemptoRunner.run(TemptoRunner.java:81)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:59)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:47)
	at com.teradata.tempto.examples.TemptoExamples.main(TemptoExamples.java:30)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NoClassDefFoundError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- generated_nation -->
      </class> <!-- com.teradata.tempto.nation -->
      <class name="com.teradata.tempto.sample_table_insert">
        <test-method status="FAIL" signature="insert_0()[pri:0, instance:com.teradata.tempto.sample_table_insert@1196950e]" test-instance-name="sql_tests.testcases.sample_table_insert.insert_0" name="insert_0" duration-ms="15525" started-at="2015-10-05T13:31:21Z" finished-at="2015-10-05T13:31:36Z">
          <exception class="java.lang.NoClassDefFoundError">
            <message>
              <![CDATA[com/facebook/presto/hive/$internal/com/google/common/primitives/Ints]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NoClassDefFoundError: com/facebook/presto/hive/$internal/com/google/common/primitives/Ints
	at org.apache.hive.service.cli.Column.<init>(Column.java:149)
	at org.apache.hive.service.cli.ColumnBasedSet.<init>(ColumnBasedSet.java:51)
	at org.apache.hive.service.cli.RowSetFactory.create(RowSetFactory.java:37)
	at org.apache.hive.jdbc.HiveQueryResultSet.next(HiveQueryResultSet.java:333)
	at com.teradata.tempto.query.QueryResult$QueryResultBuilder.addRows(QueryResult.java:230)
	at com.teradata.tempto.query.QueryResult.forResultSet(QueryResult.java:178)
	at com.teradata.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:102)
	at com.teradata.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:85)
	at com.teradata.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:62)
	at com.teradata.tempto.internal.convention.sql.SqlQueryConventionBasedTest.runTestQuery(SqlQueryConventionBasedTest.java:116)
	at com.teradata.tempto.internal.convention.sql.SqlQueryConventionBasedTest.test(SqlQueryConventionBasedTest.java:94)
	at com.teradata.tempto.internal.convention.ConventionBasedTestProxyGenerator$ConventionBasedTestProxy.test(ConventionBasedTestProxyGenerator.java:120)
	at com.teradata.tempto.sample_table_insert.insert_0(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.teradata.tempto.runner.TemptoRunner.run(TemptoRunner.java:81)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:59)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:47)
	at com.teradata.tempto.examples.TemptoExamples.main(TemptoExamples.java:30)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NoClassDefFoundError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- insert_0 -->
        <test-method status="FAIL" signature="insert_1()[pri:0, instance:com.teradata.tempto.sample_table_insert@490dc900]" test-instance-name="sql_tests.testcases.sample_table_insert.insert_1" name="insert_1" duration-ms="19589" started-at="2015-10-05T13:31:36Z" finished-at="2015-10-05T13:31:56Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> mutableTables.sample_table_prepared  [in template "name" at line 1, column 17]

----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to be legally refer to something that's null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${mutableTables.sample_table_prepared}  [in template "name" at line 1, column 15]
----]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> mutableTables.sample_table_prepared  [in template "name" at line 1, column 17]

----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to be legally refer to something that's null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${mutableTables.sample_table_prepared}  [in template "name" at line 1, column 15]
----
	at com.teradata.tempto.internal.convention.sql.SqlQueryConventionBasedTest.resolveTemplates(SqlQueryConventionBasedTest.java:139)
	at com.teradata.tempto.internal.convention.sql.SqlQueryConventionBasedTest.runTestQuery(SqlQueryConventionBasedTest.java:115)
	at com.teradata.tempto.internal.convention.sql.SqlQueryConventionBasedTest.test(SqlQueryConventionBasedTest.java:94)
	at com.teradata.tempto.internal.convention.ConventionBasedTestProxyGenerator$ConventionBasedTestProxy.test(ConventionBasedTestProxyGenerator.java:120)
	at com.teradata.tempto.sample_table_insert.insert_1(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.teradata.tempto.runner.TemptoRunner.run(TemptoRunner.java:81)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:59)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:47)
	at com.teradata.tempto.examples.TemptoExamples.main(TemptoExamples.java:30)
Caused by: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> mutableTables.sample_table_prepared  [in template "name" at line 1, column 17]

----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to be legally refer to something that's null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
	- Failed at: ${mutableTables.sample_table_prepared}  [in template "name" at line 1, column 15]
----
	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:116)
	at freemarker.core.EvalUtil.coerceModelToString(EvalUtil.java:346)
	at freemarker.core.Expression.evalAndCoerceToString(Expression.java:82)
	at freemarker.core.DollarVariable.accept(DollarVariable.java:40)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.MixedContent.accept(MixedContent.java:62)
	at freemarker.core.Environment.visit(Environment.java:312)
	at freemarker.core.Environment.process(Environment.java:290)
	at freemarker.template.Template.process(Template.java:312)
	at com.teradata.tempto.internal.convention.sql.SqlQueryConventionBasedTest.resolveTemplates(SqlQueryConventionBasedTest.java:133)
	... 29 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- insert_1 -->
      </class> <!-- com.teradata.tempto.sample_table_insert -->
      <class name="com.teradata.tempto.sample_psql_table">
        <test-method status="PASS" signature="allRows()[pri:0, instance:com.teradata.tempto.sample_psql_table@7424a39e]" test-instance-name="sql_tests.testcases.sample_psql_table.allRows" name="allRows" duration-ms="106" started-at="2015-10-05T13:31:20Z" finished-at="2015-10-05T13:31:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- allRows -->
        <test-method status="PASS" signature="allRowsOnPsql2()[pri:0, instance:com.teradata.tempto.sample_psql_table@2526ecb7]" test-instance-name="sql_tests.testcases.sample_psql_table.allRowsOnPsql2" name="allRowsOnPsql2" duration-ms="117" started-at="2015-10-05T13:31:21Z" finished-at="2015-10-05T13:31:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- allRowsOnPsql2 -->
      </class> <!-- com.teradata.tempto.sample_psql_table -->
      <class name="com.teradata.tempto.examples.TpchDataSourceTest">
        <test-method status="FAIL" signature="testDataSource()[pri:0, instance:com.teradata.tempto.examples.TpchDataSourceTest@53e6b541]" name="testDataSource" duration-ms="132" started-at="2015-10-05T13:30:58Z" finished-at="2015-10-05T13:30:59Z">
          <exception class="org.junit.ComparisonFailure">
            <message>
              <![CDATA[expected:<"/tempto/tpch/sf-1[,]00/REGION"> but was:<"/tempto/tpch/sf-1[_]00/REGION">]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.junit.ComparisonFailure: expected:<"/tempto/tpch/sf-1[,]00/REGION"> but was:<"/tempto/tpch/sf-1[_]00/REGION">
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at com.teradata.tempto.examples.TpchDataSourceTest.testDataSource(TpchDataSourceTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.teradata.tempto.runner.TemptoRunner.run(TemptoRunner.java:81)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:59)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:47)
	at com.teradata.tempto.examples.TemptoExamples.main(TemptoExamples.java:30)
]]>
            </full-stacktrace>
          </exception> <!-- org.junit.ComparisonFailure -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDataSource -->
      </class> <!-- com.teradata.tempto.examples.TpchDataSourceTest -->
      <class name="com.teradata.tempto.allRows">
        <test-method status="FAIL" signature="query_1()[pri:0, instance:com.teradata.tempto.allRows@7dd3f20e]" test-instance-name="sql_tests.testcases.nation.allRows.query_1" name="query_1" duration-ms="802" started-at="2015-10-05T13:30:59Z" finished-at="2015-10-05T13:30:59Z">
          <exception class="java.lang.NoClassDefFoundError">
            <message>
              <![CDATA[com/facebook/presto/hive/$internal/com/google/common/primitives/Ints]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NoClassDefFoundError: com/facebook/presto/hive/$internal/com/google/common/primitives/Ints
	at org.apache.hive.service.cli.Column.<init>(Column.java:149)
	at org.apache.hive.service.cli.ColumnBasedSet.<init>(ColumnBasedSet.java:51)
	at org.apache.hive.service.cli.RowSetFactory.create(RowSetFactory.java:37)
	at org.apache.hive.jdbc.HiveQueryResultSet.next(HiveQueryResultSet.java:333)
	at com.teradata.tempto.query.QueryResult$QueryResultBuilder.addRows(QueryResult.java:230)
	at com.teradata.tempto.query.QueryResult.forResultSet(QueryResult.java:178)
	at com.teradata.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:102)
	at com.teradata.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:85)
	at com.teradata.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:62)
	at com.teradata.tempto.internal.convention.sql.SqlQueryConventionBasedTest.runTestQuery(SqlQueryConventionBasedTest.java:116)
	at com.teradata.tempto.internal.convention.sql.SqlQueryConventionBasedTest.test(SqlQueryConventionBasedTest.java:94)
	at com.teradata.tempto.internal.convention.ConventionBasedTestProxyGenerator$ConventionBasedTestProxy.test(ConventionBasedTestProxyGenerator.java:120)
	at com.teradata.tempto.allRows.query_1(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.teradata.tempto.runner.TemptoRunner.run(TemptoRunner.java:81)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:59)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:47)
	at com.teradata.tempto.examples.TemptoExamples.main(TemptoExamples.java:30)
Caused by: java.lang.ClassNotFoundException: com.facebook.presto.hive.$internal.com.google.common.primitives.Ints
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 38 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NoClassDefFoundError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- query_1 -->
        <test-method status="FAIL" signature="query_2()[pri:0, instance:com.teradata.tempto.allRows@1dfadb7]" test-instance-name="sql_tests.testcases.nation.allRows.query_2" name="query_2" duration-ms="20011" started-at="2015-10-05T13:30:59Z" finished-at="2015-10-05T13:31:19Z">
          <exception class="java.lang.NoClassDefFoundError">
            <message>
              <![CDATA[com/facebook/presto/hive/$internal/com/google/common/primitives/Ints]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NoClassDefFoundError: com/facebook/presto/hive/$internal/com/google/common/primitives/Ints
	at org.apache.hive.service.cli.Column.<init>(Column.java:149)
	at org.apache.hive.service.cli.ColumnBasedSet.<init>(ColumnBasedSet.java:51)
	at org.apache.hive.service.cli.RowSetFactory.create(RowSetFactory.java:37)
	at org.apache.hive.jdbc.HiveQueryResultSet.next(HiveQueryResultSet.java:333)
	at com.teradata.tempto.query.QueryResult$QueryResultBuilder.addRows(QueryResult.java:230)
	at com.teradata.tempto.query.QueryResult.forResultSet(QueryResult.java:178)
	at com.teradata.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:102)
	at com.teradata.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:85)
	at com.teradata.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:62)
	at com.teradata.tempto.internal.convention.sql.SqlQueryConventionBasedTest.runTestQuery(SqlQueryConventionBasedTest.java:116)
	at com.teradata.tempto.internal.convention.sql.SqlQueryConventionBasedTest.test(SqlQueryConventionBasedTest.java:94)
	at com.teradata.tempto.internal.convention.ConventionBasedTestProxyGenerator$ConventionBasedTestProxy.test(ConventionBasedTestProxyGenerator.java:120)
	at com.teradata.tempto.allRows.query_2(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.teradata.tempto.runner.TemptoRunner.run(TemptoRunner.java:81)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:59)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:47)
	at com.teradata.tempto.examples.TemptoExamples.main(TemptoExamples.java:30)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NoClassDefFoundError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- query_2 -->
      </class> <!-- com.teradata.tempto.allRows -->
      <class name="com.teradata.tempto.examples.SimpleQueryTest">
        <test-method status="FAIL" signature="createAndDropMutableTable()[pri:0, instance:com.teradata.tempto.examples.SimpleQueryTest@786125a6]" name="createAndDropMutableTable" duration-ms="588" started-at="2015-10-05T13:30:53Z" finished-at="2015-10-05T13:30:54Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[error invoking methods annotated with com.teradata.tempto.AfterTestWithContext]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: error invoking methods annotated with com.teradata.tempto.AfterTestWithContext
	at com.teradata.tempto.internal.initialization.TestInitializationListener.invokeMethodsAnnotatedWith(TestInitializationListener.java:277)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.runAfterWithContextMethods(TestInitializationListener.java:266)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.onTestFinished(TestInitializationListener.java:244)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.onTestSuccess(TestInitializationListener.java:219)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1703)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1683)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:697)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.teradata.tempto.runner.TemptoRunner.run(TemptoRunner.java:81)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:59)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:47)
	at com.teradata.tempto.examples.TemptoExamples.main(TemptoExamples.java:30)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.invokeMethodsAnnotatedWith(TestInitializationListener.java:274)
	... 25 more
Caused by: org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at com.teradata.tempto.examples.SimpleQueryTest.afterTest(SimpleQueryTest.java:87)
	... 30 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createAndDropMutableTable -->
        <test-method status="FAIL" signature="failingTest()[pri:0, instance:com.teradata.tempto.examples.SimpleQueryTest@786125a6]" name="failingTest" duration-ms="205" started-at="2015-10-05T13:30:54Z" finished-at="2015-10-05T13:30:54Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[error invoking methods annotated with com.teradata.tempto.AfterTestWithContext]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: error invoking methods annotated with com.teradata.tempto.AfterTestWithContext
	at com.teradata.tempto.internal.initialization.TestInitializationListener.invokeMethodsAnnotatedWith(TestInitializationListener.java:277)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.runAfterWithContextMethods(TestInitializationListener.java:266)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.onTestFinished(TestInitializationListener.java:244)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.onTestFailure(TestInitializationListener.java:226)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1699)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1683)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:697)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.teradata.tempto.runner.TemptoRunner.run(TemptoRunner.java:81)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:59)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:47)
	at com.teradata.tempto.examples.TemptoExamples.main(TemptoExamples.java:30)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.invokeMethodsAnnotatedWith(TestInitializationListener.java:274)
	... 25 more
Caused by: org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at com.teradata.tempto.examples.SimpleQueryTest.afterTest(SimpleQueryTest.java:87)
	... 30 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failingTest -->
        <test-method status="FAIL" signature="selectAllFromMultipleTables()[pri:0, instance:com.teradata.tempto.examples.SimpleQueryTest@786125a6]" name="selectAllFromMultipleTables" duration-ms="3776" started-at="2015-10-05T13:30:54Z" finished-at="2015-10-05T13:30:58Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[error invoking methods annotated with com.teradata.tempto.AfterTestWithContext]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: error invoking methods annotated with com.teradata.tempto.AfterTestWithContext
	at com.teradata.tempto.internal.initialization.TestInitializationListener.invokeMethodsAnnotatedWith(TestInitializationListener.java:277)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.runAfterWithContextMethods(TestInitializationListener.java:266)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.onTestFinished(TestInitializationListener.java:244)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.onTestFailure(TestInitializationListener.java:226)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1699)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1683)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:697)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.teradata.tempto.runner.TemptoRunner.run(TemptoRunner.java:81)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:59)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:47)
	at com.teradata.tempto.examples.TemptoExamples.main(TemptoExamples.java:30)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.invokeMethodsAnnotatedWith(TestInitializationListener.java:274)
	... 25 more
Caused by: org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at com.teradata.tempto.examples.SimpleQueryTest.afterTest(SimpleQueryTest.java:87)
	... 30 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectAllFromMultipleTables -->
        <test-method status="FAIL" signature="selectAllFromMultipleTables()[pri:0, instance:com.teradata.tempto.examples.SimpleQueryTest@786125a6]" name="selectAllFromMultipleTables" duration-ms="466" started-at="2015-10-05T13:30:58Z" finished-at="2015-10-05T13:30:58Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[error invoking methods annotated with com.teradata.tempto.AfterTestWithContext]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: error invoking methods annotated with com.teradata.tempto.AfterTestWithContext
	at com.teradata.tempto.internal.initialization.TestInitializationListener.invokeMethodsAnnotatedWith(TestInitializationListener.java:277)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.runAfterWithContextMethods(TestInitializationListener.java:266)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.onTestFinished(TestInitializationListener.java:244)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.onTestFailure(TestInitializationListener.java:226)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1699)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1683)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:697)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.teradata.tempto.runner.TemptoRunner.run(TemptoRunner.java:81)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:59)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:47)
	at com.teradata.tempto.examples.TemptoExamples.main(TemptoExamples.java:30)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.invokeMethodsAnnotatedWith(TestInitializationListener.java:274)
	... 25 more
Caused by: org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at com.teradata.tempto.examples.SimpleQueryTest.afterTest(SimpleQueryTest.java:87)
	... 30 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectAllFromMultipleTables -->
        <test-method status="FAIL" signature="selectAllFromNation()[pri:0, instance:com.teradata.tempto.examples.SimpleQueryTest@786125a6]" name="selectAllFromNation" duration-ms="184" started-at="2015-10-05T13:30:58Z" finished-at="2015-10-05T13:30:58Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[error invoking methods annotated with com.teradata.tempto.AfterTestWithContext]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: error invoking methods annotated with com.teradata.tempto.AfterTestWithContext
	at com.teradata.tempto.internal.initialization.TestInitializationListener.invokeMethodsAnnotatedWith(TestInitializationListener.java:277)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.runAfterWithContextMethods(TestInitializationListener.java:266)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.onTestFinished(TestInitializationListener.java:244)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.onTestFailure(TestInitializationListener.java:226)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1699)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1683)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:697)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.teradata.tempto.runner.TemptoRunner.run(TemptoRunner.java:81)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:59)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:47)
	at com.teradata.tempto.examples.TemptoExamples.main(TemptoExamples.java:30)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.invokeMethodsAnnotatedWith(TestInitializationListener.java:274)
	... 25 more
Caused by: org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at com.teradata.tempto.examples.SimpleQueryTest.afterTest(SimpleQueryTest.java:87)
	... 30 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectAllFromNation -->
        <test-method status="FAIL" signature="selectCountFromNation()[pri:0, instance:com.teradata.tempto.examples.SimpleQueryTest@786125a6]" name="selectCountFromNation" duration-ms="181" started-at="2015-10-05T13:30:58Z" finished-at="2015-10-05T13:30:58Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[error invoking methods annotated with com.teradata.tempto.AfterTestWithContext]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: error invoking methods annotated with com.teradata.tempto.AfterTestWithContext
	at com.teradata.tempto.internal.initialization.TestInitializationListener.invokeMethodsAnnotatedWith(TestInitializationListener.java:277)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.runAfterWithContextMethods(TestInitializationListener.java:266)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.onTestFinished(TestInitializationListener.java:244)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.onTestFailure(TestInitializationListener.java:226)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1699)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1683)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:697)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.teradata.tempto.runner.TemptoRunner.run(TemptoRunner.java:81)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:59)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:47)
	at com.teradata.tempto.examples.TemptoExamples.main(TemptoExamples.java:30)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.invokeMethodsAnnotatedWith(TestInitializationListener.java:274)
	... 25 more
Caused by: org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at com.teradata.tempto.examples.SimpleQueryTest.afterTest(SimpleQueryTest.java:87)
	... 30 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectCountFromNation -->
      </class> <!-- com.teradata.tempto.examples.SimpleQueryTest -->
      <class name="com.teradata.tempto.examples.ExampleSshClientUsage">
        <test-method status="PASS" signature="dynamicSshClient()[pri:0, instance:com.teradata.tempto.examples.ExampleSshClientUsage@3c32f3d8]" name="dynamicSshClient" duration-ms="2009" started-at="2015-10-05T13:30:45Z" finished-at="2015-10-05T13:30:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dynamicSshClient -->
        <test-method status="FAIL" signature="longRunningCommandTimeout()[pri:0, instance:com.teradata.tempto.examples.ExampleSshClientUsage@3c32f3d8]" name="longRunningCommandTimeout" duration-ms="2974" started-at="2015-10-05T13:30:47Z" finished-at="2015-10-05T13:30:50Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[
Expecting:
 <"com.jcraft.jsch.JSchException: Auth fail">
to contain:
 <"did not finish within given timeout"> ]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
Expecting:
 <"com.jcraft.jsch.JSchException: Auth fail">
to contain:
 <"did not finish within given timeout"> 
	at com.teradata.tempto.examples.ExampleSshClientUsage.longRunningCommandTimeout(ExampleSshClientUsage.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.teradata.tempto.runner.TemptoRunner.run(TemptoRunner.java:81)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:59)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:47)
	at com.teradata.tempto.examples.TemptoExamples.main(TemptoExamples.java:30)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- longRunningCommandTimeout -->
        <test-method status="FAIL" signature="sshClientUsage()[pri:0, instance:com.teradata.tempto.examples.ExampleSshClientUsage@3c32f3d8]" name="sshClientUsage" duration-ms="2516" started-at="2015-10-05T13:30:50Z" finished-at="2015-10-05T13:30:53Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[com.jcraft.jsch.JSchException: Auth fail]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: com.jcraft.jsch.JSchException: Auth fail
	at com.teradata.tempto.internal.ssh.JSchSshClient.upload(JSchSshClient.java:98)
	at com.teradata.tempto.examples.ExampleSshClientUsage.sshClientUsage(ExampleSshClientUsage.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.teradata.tempto.runner.TemptoRunner.run(TemptoRunner.java:81)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:59)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:47)
	at com.teradata.tempto.examples.TemptoExamples.main(TemptoExamples.java:30)
Caused by: com.jcraft.jsch.JSchException: Auth fail
	at com.jcraft.jsch.Session.connect(Session.java:512)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.teradata.tempto.internal.ssh.JSchSshClient.getActiveSession(JSchSshClient.java:78)
	at com.teradata.tempto.internal.ssh.JSchSshClient.upload(JSchSshClient.java:88)
	... 26 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sshClientUsage -->
      </class> <!-- com.teradata.tempto.examples.ExampleSshClientUsage -->
      <class name="com.teradata.tempto.examples.PostgresqlQueryTest">
        <test-method status="PASS" signature="selectFromImmutableTable()[pri:0, instance:com.teradata.tempto.examples.PostgresqlQueryTest@17f4276b]" name="selectFromImmutableTable" duration-ms="194" started-at="2015-10-05T13:30:53Z" finished-at="2015-10-05T13:30:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectFromImmutableTable -->
        <test-method status="PASS" signature="selectFromMutableTable()[pri:0, instance:com.teradata.tempto.examples.PostgresqlQueryTest@17f4276b]" name="selectFromMutableTable" duration-ms="166" started-at="2015-10-05T13:30:53Z" finished-at="2015-10-05T13:30:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectFromMutableTable -->
      </class> <!-- com.teradata.tempto.examples.PostgresqlQueryTest -->
      <class name="com.teradata.tempto.sample_hive_table">
        <test-method status="FAIL" signature="allRows()[pri:0, instance:com.teradata.tempto.sample_hive_table@4602fa2f]" test-instance-name="sql_tests.testcases.sample_hive_table.allRows" name="allRows" duration-ms="331" started-at="2015-10-05T13:31:20Z" finished-at="2015-10-05T13:31:20Z">
          <exception class="java.lang.NoClassDefFoundError">
            <message>
              <![CDATA[com/facebook/presto/hive/$internal/com/google/common/primitives/Ints]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NoClassDefFoundError: com/facebook/presto/hive/$internal/com/google/common/primitives/Ints
	at org.apache.hive.service.cli.Column.<init>(Column.java:149)
	at org.apache.hive.service.cli.ColumnBasedSet.<init>(ColumnBasedSet.java:51)
	at org.apache.hive.service.cli.RowSetFactory.create(RowSetFactory.java:37)
	at org.apache.hive.jdbc.HiveQueryResultSet.next(HiveQueryResultSet.java:333)
	at com.teradata.tempto.query.QueryResult$QueryResultBuilder.addRows(QueryResult.java:230)
	at com.teradata.tempto.query.QueryResult.forResultSet(QueryResult.java:178)
	at com.teradata.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:102)
	at com.teradata.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:85)
	at com.teradata.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:62)
	at com.teradata.tempto.internal.convention.sql.SqlQueryConventionBasedTest.runTestQuery(SqlQueryConventionBasedTest.java:116)
	at com.teradata.tempto.internal.convention.sql.SqlQueryConventionBasedTest.test(SqlQueryConventionBasedTest.java:94)
	at com.teradata.tempto.internal.convention.ConventionBasedTestProxyGenerator$ConventionBasedTestProxy.test(ConventionBasedTestProxyGenerator.java:120)
	at com.teradata.tempto.sample_hive_table.allRows(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.teradata.tempto.runner.TemptoRunner.run(TemptoRunner.java:81)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:59)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:47)
	at com.teradata.tempto.examples.TemptoExamples.main(TemptoExamples.java:30)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NoClassDefFoundError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- allRows -->
      </class> <!-- com.teradata.tempto.sample_hive_table -->
      <class name="com.teradata.tempto.sample_presto_table">
        <test-method status="FAIL" signature="allRows()[pri:0, instance:com.teradata.tempto.sample_presto_table@6a4bd9e4]" test-instance-name="sql_tests.testcases.sample_presto_table.allRows" name="allRows" duration-ms="165" started-at="2015-10-05T13:31:20Z" finished-at="2015-10-05T13:31:20Z">
          <exception class="com.teradata.tempto.query.QueryExecutionException">
            <message>
              <![CDATA[java.sql.SQLException: Error executing query]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.teradata.tempto.query.QueryExecutionException: java.sql.SQLException: Error executing query
	at com.teradata.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:92)
	at com.teradata.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:62)
	at com.teradata.tempto.internal.convention.sql.SqlQueryConventionBasedTest.runTestQuery(SqlQueryConventionBasedTest.java:116)
	at com.teradata.tempto.internal.convention.sql.SqlQueryConventionBasedTest.test(SqlQueryConventionBasedTest.java:94)
	at com.teradata.tempto.internal.convention.ConventionBasedTestProxyGenerator$ConventionBasedTestProxy.test(ConventionBasedTestProxyGenerator.java:120)
	at com.teradata.tempto.sample_presto_table.allRows(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.teradata.tempto.runner.TemptoRunner.run(TemptoRunner.java:81)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:59)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:47)
	at com.teradata.tempto.examples.TemptoExamples.main(TemptoExamples.java:30)
Caused by: java.sql.SQLException: Error executing query
	at com.facebook.presto.jdbc.PrestoStatement.executeQuery(PrestoStatement.java:54)
	at com.teradata.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:101)
	at com.teradata.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:85)
	... 30 more
Caused by: com.facebook.presto.jdbc.internal.airlift.http.client.RuntimeIOException: Server refused connection: http://localhost:8080/v1/statement
	at com.facebook.presto.jdbc.internal.airlift.http.client.ResponseHandlerUtils.propagate(ResponseHandlerUtils.java:17)
	at com.facebook.presto.jdbc.internal.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:55)
	at com.facebook.presto.jdbc.internal.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:35)
	at com.facebook.presto.jdbc.internal.airlift.http.client.jetty.JettyHttpClient.execute(JettyHttpClient.java:297)
	at com.facebook.presto.jdbc.internal.client.StatementClient.<init>(StatementClient.java:96)
	at com.facebook.presto.jdbc.QueryExecutor.startQuery(QueryExecutor.java:63)
	at com.facebook.presto.jdbc.PrestoConnection.startQuery(PrestoConnection.java:588)
	at com.facebook.presto.jdbc.PrestoStatement.executeQuery(PrestoStatement.java:49)
	... 32 more
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at com.facebook.presto.jdbc.internal.jetty.io.SelectorManager.finishConnect(SelectorManager.java:340)
	at com.facebook.presto.jdbc.internal.jetty.io.SelectorManager$ManagedSelector.processConnect(SelectorManager.java:671)
	at com.facebook.presto.jdbc.internal.jetty.io.SelectorManager$ManagedSelector.processKey(SelectorManager.java:640)
	at com.facebook.presto.jdbc.internal.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:607)
	at com.facebook.presto.jdbc.internal.jetty.io.SelectorManager$ManagedSelector.run(SelectorManager.java:545)
	at com.facebook.presto.jdbc.internal.jetty.util.thread.NonBlockingThread.run(NonBlockingThread.java:52)
	at com.facebook.presto.jdbc.internal.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at com.facebook.presto.jdbc.internal.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- com.teradata.tempto.query.QueryExecutionException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- allRows -->
        <test-method status="FAIL" signature="psqlOverPrestoAllRows()[pri:0, instance:com.teradata.tempto.sample_presto_table@8ea1521]" test-instance-name="sql_tests.testcases.sample_presto_table.psqlOverPrestoAllRows" name="psqlOverPrestoAllRows" duration-ms="121" started-at="2015-10-05T13:31:20Z" finished-at="2015-10-05T13:31:20Z">
          <exception class="com.teradata.tempto.query.QueryExecutionException">
            <message>
              <![CDATA[java.sql.SQLException: Error executing query]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.teradata.tempto.query.QueryExecutionException: java.sql.SQLException: Error executing query
	at com.teradata.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:92)
	at com.teradata.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:62)
	at com.teradata.tempto.internal.convention.sql.SqlQueryConventionBasedTest.runTestQuery(SqlQueryConventionBasedTest.java:116)
	at com.teradata.tempto.internal.convention.sql.SqlQueryConventionBasedTest.test(SqlQueryConventionBasedTest.java:94)
	at com.teradata.tempto.internal.convention.ConventionBasedTestProxyGenerator$ConventionBasedTestProxy.test(ConventionBasedTestProxyGenerator.java:120)
	at com.teradata.tempto.sample_presto_table.psqlOverPrestoAllRows(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.teradata.tempto.runner.TemptoRunner.run(TemptoRunner.java:81)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:59)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:47)
	at com.teradata.tempto.examples.TemptoExamples.main(TemptoExamples.java:30)
Caused by: java.sql.SQLException: Error executing query
	at com.facebook.presto.jdbc.PrestoStatement.executeQuery(PrestoStatement.java:54)
	at com.teradata.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:101)
	at com.teradata.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:85)
	... 30 more
Caused by: com.facebook.presto.jdbc.internal.airlift.http.client.RuntimeIOException: Server refused connection: http://localhost:8080/v1/statement
	at com.facebook.presto.jdbc.internal.airlift.http.client.ResponseHandlerUtils.propagate(ResponseHandlerUtils.java:17)
	at com.facebook.presto.jdbc.internal.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:55)
	at com.facebook.presto.jdbc.internal.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:35)
	at com.facebook.presto.jdbc.internal.airlift.http.client.jetty.JettyHttpClient.execute(JettyHttpClient.java:297)
	at com.facebook.presto.jdbc.internal.client.StatementClient.<init>(StatementClient.java:96)
	at com.facebook.presto.jdbc.QueryExecutor.startQuery(QueryExecutor.java:63)
	at com.facebook.presto.jdbc.PrestoConnection.startQuery(PrestoConnection.java:588)
	at com.facebook.presto.jdbc.PrestoStatement.executeQuery(PrestoStatement.java:49)
	... 32 more
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at com.facebook.presto.jdbc.internal.jetty.io.SelectorManager.finishConnect(SelectorManager.java:340)
	at com.facebook.presto.jdbc.internal.jetty.io.SelectorManager$ManagedSelector.processConnect(SelectorManager.java:671)
	at com.facebook.presto.jdbc.internal.jetty.io.SelectorManager$ManagedSelector.processKey(SelectorManager.java:640)
	at com.facebook.presto.jdbc.internal.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:607)
	at com.facebook.presto.jdbc.internal.jetty.io.SelectorManager$ManagedSelector.run(SelectorManager.java:545)
	at com.facebook.presto.jdbc.internal.jetty.util.thread.NonBlockingThread.run(NonBlockingThread.java:52)
	at com.facebook.presto.jdbc.internal.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at com.facebook.presto.jdbc.internal.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- com.teradata.tempto.query.QueryExecutionException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- psqlOverPrestoAllRows -->
      </class> <!-- com.teradata.tempto.sample_presto_table -->
    </test> <!-- all -->
  </suite> <!-- tempto-tests -->
</testng-results>
