<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="eiger.td.teradata.com" name="com.teradata.tempto.examples.SimpleQueryTest" tests="6" failures="0" timestamp="5 Oct 2015 17:31:56 GMT" time="5.400" errors="6">
  <testcase name="selectAllFromMultipleTables" time="3.776" classname="com.teradata.tempto.examples.SimpleQueryTest">
    <error type="java.lang.RuntimeException" message="error invoking methods annotated with com.teradata.tempto.AfterTestWithContext">
      <![CDATA[java.lang.RuntimeException: error invoking methods annotated with com.teradata.tempto.AfterTestWithContext
	at com.teradata.tempto.internal.initialization.TestInitializationListener.invokeMethodsAnnotatedWith(TestInitializationListener.java:277)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.runAfterWithContextMethods(TestInitializationListener.java:266)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.onTestFinished(TestInitializationListener.java:244)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.onTestFailure(TestInitializationListener.java:226)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1699)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1683)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:697)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.teradata.tempto.runner.TemptoRunner.run(TemptoRunner.java:81)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:59)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:47)
	at com.teradata.tempto.examples.TemptoExamples.main(TemptoExamples.java:30)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.invokeMethodsAnnotatedWith(TestInitializationListener.java:274)
	... 25 more
Caused by: org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at com.teradata.tempto.examples.SimpleQueryTest.afterTest(SimpleQueryTest.java:87)
	... 30 more
]]>
    </error>
  </testcase> <!-- selectAllFromMultipleTables -->
  <testcase name="selectAllFromMultipleTables" time="0.466" classname="com.teradata.tempto.examples.SimpleQueryTest">
    <error type="java.lang.RuntimeException" message="error invoking methods annotated with com.teradata.tempto.AfterTestWithContext">
      <![CDATA[java.lang.RuntimeException: error invoking methods annotated with com.teradata.tempto.AfterTestWithContext
	at com.teradata.tempto.internal.initialization.TestInitializationListener.invokeMethodsAnnotatedWith(TestInitializationListener.java:277)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.runAfterWithContextMethods(TestInitializationListener.java:266)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.onTestFinished(TestInitializationListener.java:244)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.onTestFailure(TestInitializationListener.java:226)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1699)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1683)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:697)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.teradata.tempto.runner.TemptoRunner.run(TemptoRunner.java:81)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:59)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:47)
	at com.teradata.tempto.examples.TemptoExamples.main(TemptoExamples.java:30)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.invokeMethodsAnnotatedWith(TestInitializationListener.java:274)
	... 25 more
Caused by: org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at com.teradata.tempto.examples.SimpleQueryTest.afterTest(SimpleQueryTest.java:87)
	... 30 more
]]>
    </error>
  </testcase> <!-- selectAllFromMultipleTables -->
  <testcase name="selectCountFromNation" time="0.181" classname="com.teradata.tempto.examples.SimpleQueryTest">
    <error type="java.lang.RuntimeException" message="error invoking methods annotated with com.teradata.tempto.AfterTestWithContext">
      <![CDATA[java.lang.RuntimeException: error invoking methods annotated with com.teradata.tempto.AfterTestWithContext
	at com.teradata.tempto.internal.initialization.TestInitializationListener.invokeMethodsAnnotatedWith(TestInitializationListener.java:277)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.runAfterWithContextMethods(TestInitializationListener.java:266)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.onTestFinished(TestInitializationListener.java:244)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.onTestFailure(TestInitializationListener.java:226)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1699)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1683)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:697)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.teradata.tempto.runner.TemptoRunner.run(TemptoRunner.java:81)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:59)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:47)
	at com.teradata.tempto.examples.TemptoExamples.main(TemptoExamples.java:30)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.invokeMethodsAnnotatedWith(TestInitializationListener.java:274)
	... 25 more
Caused by: org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at com.teradata.tempto.examples.SimpleQueryTest.afterTest(SimpleQueryTest.java:87)
	... 30 more
]]>
    </error>
  </testcase> <!-- selectCountFromNation -->
  <testcase name="createAndDropMutableTable" time="0.588" classname="com.teradata.tempto.examples.SimpleQueryTest">
    <error type="java.lang.RuntimeException" message="error invoking methods annotated with com.teradata.tempto.AfterTestWithContext">
      <![CDATA[java.lang.RuntimeException: error invoking methods annotated with com.teradata.tempto.AfterTestWithContext
	at com.teradata.tempto.internal.initialization.TestInitializationListener.invokeMethodsAnnotatedWith(TestInitializationListener.java:277)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.runAfterWithContextMethods(TestInitializationListener.java:266)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.onTestFinished(TestInitializationListener.java:244)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.onTestSuccess(TestInitializationListener.java:219)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1703)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1683)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:697)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.teradata.tempto.runner.TemptoRunner.run(TemptoRunner.java:81)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:59)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:47)
	at com.teradata.tempto.examples.TemptoExamples.main(TemptoExamples.java:30)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.invokeMethodsAnnotatedWith(TestInitializationListener.java:274)
	... 25 more
Caused by: org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at com.teradata.tempto.examples.SimpleQueryTest.afterTest(SimpleQueryTest.java:87)
	... 30 more
]]>
    </error>
  </testcase> <!-- createAndDropMutableTable -->
  <testcase name="failingTest" time="0.205" classname="com.teradata.tempto.examples.SimpleQueryTest">
    <error type="java.lang.RuntimeException" message="error invoking methods annotated with com.teradata.tempto.AfterTestWithContext">
      <![CDATA[java.lang.RuntimeException: error invoking methods annotated with com.teradata.tempto.AfterTestWithContext
	at com.teradata.tempto.internal.initialization.TestInitializationListener.invokeMethodsAnnotatedWith(TestInitializationListener.java:277)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.runAfterWithContextMethods(TestInitializationListener.java:266)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.onTestFinished(TestInitializationListener.java:244)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.onTestFailure(TestInitializationListener.java:226)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1699)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1683)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:697)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.teradata.tempto.runner.TemptoRunner.run(TemptoRunner.java:81)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:59)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:47)
	at com.teradata.tempto.examples.TemptoExamples.main(TemptoExamples.java:30)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.invokeMethodsAnnotatedWith(TestInitializationListener.java:274)
	... 25 more
Caused by: org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at com.teradata.tempto.examples.SimpleQueryTest.afterTest(SimpleQueryTest.java:87)
	... 30 more
]]>
    </error>
  </testcase> <!-- failingTest -->
  <testcase name="selectAllFromNation" time="0.184" classname="com.teradata.tempto.examples.SimpleQueryTest">
    <error type="java.lang.RuntimeException" message="error invoking methods annotated with com.teradata.tempto.AfterTestWithContext">
      <![CDATA[java.lang.RuntimeException: error invoking methods annotated with com.teradata.tempto.AfterTestWithContext
	at com.teradata.tempto.internal.initialization.TestInitializationListener.invokeMethodsAnnotatedWith(TestInitializationListener.java:277)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.runAfterWithContextMethods(TestInitializationListener.java:266)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.onTestFinished(TestInitializationListener.java:244)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.onTestFailure(TestInitializationListener.java:226)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1699)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1683)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:697)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.teradata.tempto.runner.TemptoRunner.run(TemptoRunner.java:81)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:59)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:47)
	at com.teradata.tempto.examples.TemptoExamples.main(TemptoExamples.java:30)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.teradata.tempto.internal.initialization.TestInitializationListener.invokeMethodsAnnotatedWith(TestInitializationListener.java:274)
	... 25 more
Caused by: org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at com.teradata.tempto.examples.SimpleQueryTest.afterTest(SimpleQueryTest.java:87)
	... 30 more
]]>
    </error>
  </testcase> <!-- selectAllFromNation -->
</testsuite> <!-- com.teradata.tempto.examples.SimpleQueryTest -->
